# Project information
site_name: My Cheatsheets
site_url: https://valsells.me/mycheatsheets/
site_author: Marc Valsells Niubó
site_description: In this site I will be adding commands cheatsheets that I think they will be useful me and others

theme:
  name: material

  # Static files
  static_templates:
    - 404.html

plugins:
  - search
  - git-revision-date

#Respository
repo_name: mvalsells/mycheatsheets
repo_url: https://github.com/mvalsells/mycheatsheets
edit_uri: edit/main/docs


# Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
