name: publish-site
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip3 install mkdocs-material
      - run: pip3 install mkdocs-git-revision-date-plugin
      - run: mkdocs gh-deploy --force
